In [4]:
print("hello")

hello

In [5]:
from os import path
main_path='t2-ragbench/data/ConvFinQA'

json_path=path.join(main_path,'turn_0.jsonl')

In [6]:
import json

def Load_josn(p):
    with open(p, 'r', encoding='utf-8') as f:
        d = json.load(f)
    return d


pdf_urls=Load_josn('data_set\\pdf_urls.json')
question_doc = Load_josn('data_set\\qrels.json')
queries=Load_josn('data_set\\queries.json')
answers=Load_josn('data_set\\answers.json')

In [7]:
import pandas as pd
df = pd.DataFrame.from_dict(question_doc, orient='index')
df.index.name = 'query_id'
df = df.reset_index()  

print(df)

                                  query_id        doc_id  section_id
0     852703f0-8373-43a2-a18a-eb5908ad0779  2410.14077v2           1
1     9199173b-3ed1-4118-88cd-1713fc5fa8a7  2404.00822v2          17
2     1d585069-a446-47fa-a74d-0387316ea330  2410.07168v2          30
3     dc064d11-cd18-4866-8a99-f16b0abec9c6  2401.07294v4          12
4     283afa84-f0c8-40a7-a6f1-fb2a6b97c761  2411.14884v3           1
...                                    ...           ...         ...
3040  08a34950-7004-433d-ac0e-8c48363ce406  2410.23587v3           2
3041  029ae88b-dc53-4f88-918b-c8478d7ef0d3  2410.12710v2           2
3042  d369250a-8506-4c6c-948b-e9383e88e0e2  2410.10516v3          15
3043  6d7c948c-4d17-4b27-bb83-eb2b88728035  2408.02322v2           0
3044  90144eed-61dd-4a4a-b85d-0e01d597004a  2403.12117v2          27

[3045 rows x 3 columns]

In [8]:
doc_list=df.groupby('doc_id').count().sort_values(by='query_id',ascending=False).head(10).index.tolist()
df=df[df['doc_id'].isin(doc_list)]

In [ ]:
import requests, os
from concurrent.futures import ThreadPoolExecutor, as_completed

os.makedirs("pdfs", exist_ok=True)
items ={}
for i ,j in pdf_urls.items():
    if(i in doc_list):
        items[i]=j
    
def download(name_url):
    name, url = name_url
    try:
        fname = os.path.join("pdfs", f"{name}.pdf")
        
        res = requests.get(url, timeout=30)
        res.raise_for_status()
        with open(fname, "wb") as f:
            f.write(res.content)
        return name, True, None
    except Exception as e:
        return name, False, str(e)

pdfs_ = []
with ThreadPoolExecutor(max_workers=8) as executor:
    futures = [executor.submit(download, item) for item in items.items()]
    for future in as_completed(futures):
        name, ok, err = future.result()
        if ok:
            pdfs_.append(name)
        else:
            print(f"failed: {name} -> {err}")

print(f"{len(pdfs_)}/{len(items)} downloaded")

In [9]:
q_df = pd.DataFrame.from_dict(queries, orient='index')  # columns: query, type, source
q_df.index.name = 'query_id'
q_df = q_df.reset_index().rename(columns={'type': 'query_type', 'source': 'query_source', 'query': 'query'})

df = df.merge(q_df, on='query_id', how='left')

In [10]:
answer_df=pd.DataFrame.from_dict(answers,orient="index")
answer_df.index.name='query_id'
df=df.merge(answer_df,on='query_id',how='left')

In [11]:
df=df.rename(columns={0:'answer'})

In [12]:
df.head(2)

,query_id,doc_id,section_id,query,query_type,query_source,answer
0,dc064d11-cd18-4866-8a99-f16b0abec9c6,2401.07294v4,12,How does the MLMM approach affect the analysis...,abstractive,text-image,The MLMM approach affects the analysis of RMSE...
1,bac61451-d99a-43b3-9754-b8a593e5d1d7,2401.11899v3,10,Does bounded invariance affect how probability...,extractive,text,"No, bounded invariance states that changes in ..."

In [13]:
from rag_eval.parsers import PDFPlumberParser

In [14]:
p=PDFPlumberParser()

In [15]:
d=p.parse('D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf')

In [16]:
d.pages[0].content

'Leveraging IS and TC: Optimal order execution subject to\nreference strategies\nXue Cheng1, Peng Guo1, and Tai-Ho Wang2\n1\nLMEQF,DepartmentofFinancialMathematics,SchoolofMathematicalSciences,PekingUniversity,Beijing100871,China.\n2DepartmentofMathematics,BaruchCollege,CUNY,1BernardBaruchWay,NewYork,NY10010,USA\nMarch 5, 2025\nAbstract\nThe paper addresses the problem of meta order execution from a broker-dealer’s point of view in\nAlmgren-Chriss model under execution risk. A broker-dealer agency is authorized to execute an order\nof trading on some client’s behalf. The strategies that the agent is allowed to deploy is subject to a\nbenchmark, referred to as the reference strategy, regulated by the client. We formulate the broker’s\nproblem as a utility maximization problem in which the broker seeks to maximize his utility of excess\nprofit-and-lossattheexecutionhorizon,ofwhichoptimalfeedbackstrategiesareobtainedinclosedform.\nIn the absence of execution risk, the optimal strategies subject to reference strategies are deterministic.\nWeestablishanaffinestructureamongthetradingtrajectoriesunderoptimalstrategiessubjecttogeneral\nreferencestrategiesusingimplementationshortfall(IS)andtargetclose(TC)ordersasbasis. Furthermore,\nan approximation theorem is proposed to show that with small error, general reference strategies can be\napproximated by piece-wise constant ones, of which the optimal strategy is piece-wise linear combination\nbetween IS and TC orders. We conclude the paper with numerical experiments illustrating the trading\ntrajectories as well as histograms of terminal wealth and utility at investment horizon under optimal\nstrategies versus those under TWAP strategies.\nKeywords: Optimal execution; Price impact; Execution risk; Utility maximization; Reference strategy;\nAffine structure; Implementation shortfall order; Target close order\nContents\n1 Introduction 3\n2 Model setup 5\n2.1 Price impact model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5\n2.2 Reference strategy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6\n3 Optimal execution as utility maximizing 7\n3.1 Optimal execution with risk aversion . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7\n1\n5202\nraM\n4\n]RT.nif-q[\n2v50330.1042:viXra'

In [17]:
from rag_eval.chunkers import RecursiveChunker

r=RecursiveChunker()
chunks_=r.chunk(d)

In [18]:
chunks_

[Chunk(text='Leveraging IS and TC: Optimal order execution subject to\nreference strategies\nXue Cheng1, Peng Guo1, and Tai-Ho Wang2\n1\nLMEQF,DepartmentofFinancialMathematics,SchoolofMathematicalSciences,PekingUniversity,Beijing100871,China.\n2DepartmentofMathematics,BaruchCollege,CUNY,1BernardBaruchWay,NewYork,NY10010,USA\nMarch 5, 2025\nAbstract\nThe paper addresses the problem of meta order execution from a broker-dealer’s point of view in', chunk_no=0, page_numbers=[1], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='Almgren-Chriss model under execution risk. A broker-dealer agency is authorized to execute an order\nof trading on some client’s behalf. The strategies that the agent is allowed to deploy is subject to a\nbenchmark, referred to as the reference strategy, regulated by the client. We formulate the broker’s\nproblem as a utility maximization problem in which the broker seeks to maximize his utility of excess\nprofit-and-lossattheexecutionhorizon,ofwhichoptimalfeedbackstrategiesareobtainedinclosedform.', chunk_no=1, page_numbers=[1], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='In the absence of execution risk, the optimal strategies subject to reference strategies are deterministic.\nWeestablishanaffinestructureamongthetradingtrajectoriesunderoptimalstrategiessubjecttogeneral\nreferencestrategiesusingimplementationshortfall(IS)andtargetclose(TC)ordersasbasis. Furthermore,\nan approximation theorem is proposed to show that with small error, general reference strategies can be', chunk_no=2, page_numbers=[1], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='approximated by piece-wise constant ones, of which the optimal strategy is piece-wise linear combination\nbetween IS and TC orders. We conclude the paper with numerical experiments illustrating the trading\ntrajectories as well as histograms of terminal wealth and utility at investment horizon under optimal\nstrategies versus those under TWAP strategies.\nKeywords: Optimal execution; Price impact; Execution risk; Utility maximization; Reference strategy;', chunk_no=3, page_numbers=[1], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='Affine structure; Implementation shortfall order; Target close order\nContents\n1 Introduction 3\n2 Model setup 5\n2.1 Price impact model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5\n2.2 Reference strategy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6\n3 Optimal execution as utility maximizing 7\n3.1 Optimal execution with risk aversion . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7\n1\n5202\nraM\n4', chunk_no=4, page_numbers=[1], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='1\n5202\nraM\n4\n]RT.nif-q[\n2v50330.1042:viXra', chunk_no=5, page_numbers=[1], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='4 Zero execution risk 10\n4.1 General reference strategy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11\n4.2 Implementation shortfall (IS) order and target close (TC) order . . . . . . . . . . . . . . . . . . 12\n4.3 Endpoints-only reference strategy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14\n4.4 Piece-wise constant reference strategy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16\n5 Numerical examples 18', chunk_no=6, page_numbers=[2], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='5 Numerical examples 18\n5.1 Sample trading trajectories . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18\n5.2 Performance analysis and stress test . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 22\n6 Conclusion 25\nA Appendix 25\n2', chunk_no=7, page_numbers=[2], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='1 Introduction\nIn the financial industry, large position holders such as pension funds or investment banks for various reasons\nare required to trade in or trade out from their current position to an updated target, possibly subject to a\ngiven execution horizon which may vary from days to weeks. The net holdings to be adjusted between the\ncurrent and the target positions are usually too large to be simply dumped to the market without a priori', chunk_no=8, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='deliberately assessing the trade’s market impact. Untamed price impact by trading may result in significant\ntransaction cost, potentially turned into a substantial loss. Such an execution risk requires to be properly\nmanaged and controlled; otherwise it would eventually influence the position holder’s overall profit and loss\n(P&L).Acommonpracticeistodelegatetheexecutiontothefirm’sorderexecutiondepartmentoroutsource\nto a broker-dealer agency.', chunk_no=9, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='to a broker-dealer agency.\nThe large position holders, while delegating their tasks to an agency for execution, may have in mind\ntheir own preferred strategies or benchmarks that they would like the delegated agent to closely track along.\nFor instance, implementation shortfall (IS) orders [1] are frequently employed by managers for the purpose\nof short-term alpha pursuit. IS orders are constructed with a pre-trade benchmark price in mind, aiming at', chunk_no=10, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='executing orders at an average price that remains relatively close to the market price at the beginning of the\ntrade. Managers can often use arrival prices to help measure total trading costs: the closer the execution\nprice is to the arrival price, the lower the associated costs (see CFA-level-II [2]). On the contrary, target close\n(TC) orders [3], often deployed by index-fund managers for the purpose of minimizing fund risk and tracking', chunk_no=11, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='error, are formulated with a post-trade benchmark price in order to secure a price in average that remains\nrelatively close to the closing price. This is often important for mutual fund managers who manage funds\nthat only calculate NAV once daily at closing. Volume weighted average price (VWAP) and Time weighted\naverage price (TWAP) strategies are benchmarks specified for trading sequences with constant trading rate', chunk_no=12, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='in wall clock time (TWAP) and in volume time (VWAP) respectively. These algorithmic trading strategies\nare examples of benchmarks that may be imposed as trading constraints to the agent who is missioned to\ntrade in or trade out the position. We shall delve into this type of order execution problems subject to a\npre-specified benchmark strategy, which we refer to as the reference strategy (RS for short), as a stochastic', chunk_no=13, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='control problem and determine their corresponding optimal strategies in feedback form.\nThepioneeringworksin[4], [1], [5]and[6]areamongthefirsttodealwiththeproblemoforderexecution\nunderpriceimpact. Sinceitsintroductiontotheorderexecutionproblem,numerousprogressesandextensions\non the classical Almgren-Chriss framework have been made extensively. For instance, [7] and [8] introduced\nthe notion of transient impact to account for the dissipation of price impacts from the past trades. [9]', chunk_no=14, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='discussesthe objective intheoptimizationproblem, while[10]extendsthe classicalmean-variance framework\nfirst considered in [4] to encompass general risk measures as penalty for risk aversion. [11], [12], [13] solve the\noptimal execution problem in relation to a VWAP benchmark, while [14] asserts the use of the arrival price\nas a benchmark within the Almgren-Chriss framework. In fact, the arrival price, also known as “pre-trade', chunk_no=15, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='benchmark”, appears to be the most commonly used benchmark in academic papers. The closing price is\nthe value of a security at its last transaction during a trading session [3] [15]. Average price benchmarks\nmay also appear in accelerated share repurchase (ASR) contracts [16][17], which can be regarded as optimal\nexecution problems with optimal stopping. Above all, [18] introduces the concept of execution risk, that\n3', chunk_no=16, page_numbers=[3], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='pre-scheduled orders may not be fully executed, of which the empirical evidence is confirmed by [19] that\ntheinventoryprocessesoftradersinvariablycontainaBrownianmotionterm, whichcontradictsthecommon\nassumption adopted in most optimal execution models that the inventory process is absolute continuous.\nAnother perspective on introducing the noise term into the inventory process is that when a centralized', chunk_no=17, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='trading desk aggregates order flows within a financial institution, stochastic order flow arises [20] [21]. The\naforementionedpapersarebynomeansmeantforanexhaustinglistinliteratureonthislineofactiveresearch.\nInthecurrentpaper,weconsidertheorderexecutionproblemfromabroker-dealer’spointofview. Assume\nthat a broker is delegated to reallocate a client’s holdings of a certain stock under the Almgren-Chriss model', chunk_no=18, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='with execution risk. The broker is regulated by his client to track a benchmark strategy, i.e., the reference\nstrategy,totheclient’spreference. Thebroker’sincentiveofexecutingclient’sorderinthiscircumstanceisto\nmaximize his own expected P&L excess to that of the reference strategy, marked-to-market. To account for\nriskaversion,werecastthebroker’sorderexecutionproblemasautilitymaximizationproblemand,incertain', chunk_no=19, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='cases, are able to solve the problem in closed form. In particular, when execution risk vanishes, or becomes\nnegligible, we show that there exists an “affine structure” among the optimal strategies induced from various\nreferencestrategies. Thisalgebraicstructureissupposedtohelpthebrokerforconcoctingandunderstanding\noptimal strategies subject to client’s general reference strategies. We argue that the framework is highly', chunk_no=20, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='versatile in the sense that it encompasses commonly deployed execution strategies such as IS, TC as well as\nTWAP and VWAP orders as special cases for benchmarking. As per the algebraic structure, it follows that,\nfor any given continuous reference strategy which can be approximated by a piece-wise constant function, we\nshow that its corresponding optimal strategy can also be approximated by those induced from the piece-wise\nconstant strategies.', chunk_no=21, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='constant strategies.\nThe rest of the paper is organized as follows. In Section 2, we lay out the price impact model of Almgren-\nChrissunderexecutionriskandincorporatereferencestrategiesintotheproblemoforderexecution. Section3\npresents the optimal feedback control of the order execution problem in Theorem 1 as one of the main results\nin the paper. Section 4 focuses and provides detailed discussions on the optimal strategies when execution', chunk_no=22, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='risk vanishes. Reference strategies and their associated optimal strategies considered in Section 4 include IS\nand TC orders as well as piece-wise constant strategies. The emphasis is put on an “affine structure” among\nthe trading trajectories induced by general reference strategies using unit IS and unit TC orders as a basis.\nNumerical examples illustrating the trading trajectories and the performance analysis under the optimal and', chunk_no=23, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='TWAPstrategiesareshownanddiscussedinSection5. Forthesakeofsmoothreading,technicalproofsofall\nthe theorems, propositions and lemmas are postponed and collected till the end of the paper as an appendix\nin Section A.\nThroughoutthepaper,(Ω,F,P)denotesacompleteprobabilityspaceequippedwithafiltrationdescribing\nthe information structure F:={F } , where t is the time variable and T >0 the fixed finite liquidation\nt t∈[0,T]', chunk_no=24, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='t t∈[0,T]\nhorizon. Let {W ,Z } be a two-dimensional Brownian motion with constant correlation ρ defined on\nt t t∈[0,T]\n(Ω,F,P). The filtration F is generated by the trajectories of the above Brownian motion, completed with all\nP-null measure sets of F.\n4', chunk_no=25, page_numbers=[4], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='2 Model setup\n2.1 Price impact model\nAssume a broker is delegated to reallocate a client’s holdings of a certain stock from x shares to A shares\n0\nwithin a given horizon T. Let x be the number of shares the broker holds at time t ∈ [0,T] during the\nt\nreallocation process and S(cid:101)t the transacted price at time t. The price dynamic is assumed to follow the\nAlmgren–Chriss model [4] [1] [5]. In the Almgren–Chriss framework, the transacted price S(cid:101)t consists of the', chunk_no=26, page_numbers=[5], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='fair price S and a slippage. The fair price S is driven by the SDE\nt t\ndS =µdt+γdx +σdW ,\nt t t\nor equivalently,\nS =S +µt+γ(x −x )+σW ,\nt 0 t 0 t\nwhere µt describes the tendency of the stock and (W ) is a standard Brownian motion. The term\nt t∈[0,T]\nγ(x −x ), for γ ≥ 0, is usually referred to as the permanent impact. Penalized by a price slippage, the\nt 0\ntransacted price is thus given by\nS(cid:101)t =S\nt\n−ηv\nt\n,', chunk_no=27, page_numbers=[5], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='S(cid:101)t =S\nt\n−ηv\nt\n,\nwhere v denotes the broker’s intended trading rate at the instant t. The slippage −ηv , for η ≥ 0, is\nt t\nalso referred to as the temporary impact. We remark that in the original setting of Almgren-Chriss and\nits extensions, the trading rate v plays a dual role. On the one hand, it serves as the realized trading\nt\nrate per the relationship v = −x˙ between x and v . On the other hand, it is regarded as the control\nt t t t', chunk_no=28, page_numbers=[5], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='t t t t\nvariable in the problem of optimal execution. These two seemingly distinct roles coincide if all the scheduled\norders are guaranteed fully executed. However, in reality it is well noticed among practitioners that, while\nexecuting a sequence of pre-scheduled orders, the orders in the sequence may not be fully executed, resulting\nin an uncontrollable realized order flow. This introduces an additional risk to the order execution problem,', chunk_no=29, page_numbers=[5], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='the execution risk. To account for this uncertainty, we introduce a noise component driven by a correlated\nBrownian motion Z into the dynamic of the position x as\nt t\ndx =−v dt+m(v )dZ .\nt t t t\nThe diffusion term m(v) characterizes the magnitude of execution risk. It is worth to reiterate that in a\nrecent work in [19], the authors showed that the presence of a Brownian component in the broker’s inventory', chunk_no=30, page_numbers=[5], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='during reallocation process is statistically significant. Moreover, because of this execution risk, the broker is\nnolongerguaranteedtoachievehisintendedpositionattheterminaltimeT,whichgivesrisetoanadditional\nopportunity cost. As a result, the broker is obligated to take a final block trade at time T at a worse price.\nOverall, the realised P&L at the horizon T is given by\n(cid:90) T (cid:16) (cid:17)\nΠ:=(x −A)S −β(x −A)2+ −S˜ dx ,\nT T T t t\n0\n5', chunk_no=31, page_numbers=[5], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='where the term β(x −A)2, for β ≥0, penalizes the discrepency from a final block trade.\nT\nThe following proposition shows that the P&L can be written as an Itô process.\nProposition 1. The realised P&L can be rewritten as\n(cid:90) T\nΠ=(x −A)S −β(x −A)2+ (cid:0) µ(x −A)+ρσm(v )−ηv2−γv (x −A) (cid:1) dt\n0 0 T t t t t t\n0\n(cid:90) T (cid:90) T\n+ σ(x −A)dW + (ηv +γ(x −A))m(v )dZ .\nt t t t t t\n0 0\n2.2 Reference strategy', chunk_no=32, page_numbers=[6], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='t t t t t t\n0 0\n2.2 Reference strategy\nA common practice in order execution brokerage is that clients may come forward to brokers with their\nown preferred strategies for benchmarking. These benchmark strategies can be either strategies suggested\nby elite investors or commonly used ones such as TWAP strategies. We shall refer to these pre-specified\nbenchmark strategies as reference strategies. We consider the reference strategies that can be represented by', chunk_no=33, page_numbers=[6], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='a deterministic function (R ) with R ≡ x and R ≡ A hereafter. Moreover, we assume that R is\nt t∈[0,T] 0 0 T t\na differentiable a.e. function. The broker’s incentive of executing client’s order is thus to maximize his own\nexpected P&L excess to that of the reference strategy, marked-to-market. Specifically, by disregarding the\nprice impact and slippages incurred from order execution, the stock price S0 reads\nt\nS0 =S +µt+σW .\nt 0 t', chunk_no=34, page_numbers=[6], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),
 Chunk(text='t\nS0 =S +µt+σW .\nt 0 t\nThe marked-to-market P&L ΠR for the reference strategy R is evaluated as\n(cid:90) T\nΠR := (cid:0) −S0(cid:1)dR\nt t\n0\n(cid:90) T\n=−(S t 0R t ) (cid:12) (cid:12) T 0 + R t (µdt+σdW t )\n0\n(cid:90) T (cid:90) T\n=−AS0 +x S + µR dt+ σR dW\nT 0 0 t t t\n0 0\n(cid:90) T (cid:90) T\n=(x −A)S + µ(R −A)dt+ σ(R −A)dW .\n0 0 t t t\n0 0\nHence, the broker’s excess P&L Π˜, defined by the difference between Π and ΠR, is given by\nΠ˜ :=Π−ΠR\n(cid:90) T', chunk_no=35, page_numbers=[6], source_id='D:\\projects\\RAG-Chunking-Eval\\pdfs\\2401.03305v2.pdf', metadata={}),

In [35]:
q1_df=df[df['doc_id']=='2401.03305v2']

In [36]:
print("hello")

hello

In [38]:

from rag_eval.embedders import HuggingFaceEmbedder
he=HuggingFaceEmbedder()
chunks_df=pd.DataFrame(columns=['doc_id','doc_path','chunk','page_no','chunk_no','embedding'])
chunk_data=[]

for i in chunks_:
    chunk_data.append({'doc_id':i.source_id,'doc_path':'','page_no':i.page_numbers,'chunk':i.text,'chunk_no':i.chunk_no,'embedding':he.embed_query(i.text)})

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3484.77it/s]

In [39]:
q1_df["embedding"] = q1_df.apply(
    lambda x: he.embed_query(x["query"]),
    axis=1
)

C:\Users\vishw\AppData\Local\Temp\ipykernel_4564\3761716432.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q1_df["embedding"] = q1_df.apply(

In [40]:
q1_df.columns

Index(['query_id', 'doc_id', 'section_id', 'query', 'query_type',
       'query_source', 'answer', 'embedding'],
      dtype='object')

In [41]:
chunks_df.columns

Index(['doc_id', 'doc_path', 'chunk', 'page_no', 'chunk_no', 'embedding'], dtype='object')

In [44]:
q1_df.head(1)

,query_id,doc_id,section_id,query,query_type,query_source,answer,embedding
6,0920cb6c-229b-4b46-b2ab-834dffea6689,2401.03305v2,2,How do implementation shortfall (IS) and targe...,abstractive,text,Implementation shortfall (IS) orders aim to ex...,"[-0.031133107841014862, 0.07394389063119888, 0..."

In [47]:
chunks_df=pd.DataFrame(chunk_data)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Precompute chunk embeddings ONCE outside the function
chunk_embs = np.vstack(chunks_df['embedding'].values)  # More robust than tolist()

def get_top_5_chunks(row):
    """Find top 5 most similar chunks for a query."""
    query_emb = np.array(row['embedding']).reshape(1, -1)
    
    # Cosine similarity: shape (1, num_chunks)
    similarities = cosine_similarity(query_emb, chunk_embs)[0]
    
    # Get indices of top 5
    top_indices = np.argsort(similarities)[-5:][::-1]
    
    # Return as list of dicts with chunk info + similarity score
    return [
        {
            'chunk': chunks_df.iloc[idx]['chunk'],
            'doc_id': chunks_df.iloc[idx]['doc_id'],
            'page_no': chunks_df.iloc[idx]['page_no'],
            'chunk_no': chunks_df.iloc[idx]['chunk_no'],
            'similarity': float(similarities[idx]),
        }
        for idx in top_indices
    ]

q1_df['top_5'] = q1_df.apply(get_top_5_chunks, axis=1)

C:\Users\vishw\AppData\Local\Temp\ipykernel_4564\3931682640.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  q1_df['top_5'] = q1_df.apply(get_top_5_chunks, axis=1)

In [66]:
import json

records = []
for _, row in q1_df.iterrows():
    records.append({
        'query_id': str(row['query_id']),
        'query_type': str(row['query_type']),
        'query': str(row['query']),
        'answer': str(row['answer']),
        'top_5': [
            {
                'chunk': str(c['chunk']),
                'doc_id': str(c['doc_id']),
                'page_no': c['page_no'] if not isinstance(c['page_no'], list) else c['page_no'][0],
                'similarity': float(c['similarity']),
            }
            for c in row['top_5']
        ]
    })

# Read the template HTML, replace the DATA constant, write out
with open('rag_eval_query_viewer_v2.html') as f:
    html = f.read()
html = html.replace('const DATA = [', f'const DATA = {json.dumps(records)}; const _ORIG = [')
with open('rag_viewer.html', 'w', encoding='utf-8') as f:
    f.write(html)